language: 
  - cpp
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
  - sudo apt-get update
  - pip install coala
  - pip install coala-bears

script:
  - coala --ci
